<?xml version="1.0"?>

<!DOCTYPE mriw-result-set [
	<!ELEMENT mriw-result-set (provenance,input,control,results)>
	<!ATTLIST mriw-result-set
		version CDATA #REQUIRED
	>
	<!ELEMENT provenance (program,creation,platform)>
	<!ELEMENT program EMPTY>
	<!ATTLIST program
		name CDATA #REQUIRED
		version CDATA #REQUIRED
		build-id CDATA #REQUIRED
	>
	<!ELEMENT creation EMPTY>
	<!ATTLIST creation
		user CDATA #REQUIRED
		time CDATA #REQUIRED
	>
	<!ELEMENT platform (machine,runtime)>
	<!ELEMENT machine EMPTY>
	<!ATTLIST machine
		architecture CDATA #REQUIRED
		os-name CDATA #REQUIRED
		os-type CDATA #REQUIRED
	>
	<!ELEMENT runtime EMPTY>
	<!ATTLIST runtime
		name CDATA #REQUIRED
		version CDATA #REQUIRED
	>
	<!ELEMENT input ((reference?),dynamic)>
	<!ATTLIST input
		modality CDATA #REQUIRED
		subtype CDATA #IMPLIED
	>
	<!ELEMENT reference ((file+)|raw)>
	<!ATTLIST reference
		path CDATA #IMPLIED
		study-uid CDATA #IMPLIED
	>
	<!ELEMENT dynamic (file)+>
	<!ATTLIST dynamic
		ignore CDATA #IMPLIED
		path CDATA #IMPLIED
		slices CDATA #IMPLIED
		study-uid CDATA #IMPLIED
	>
	<!ELEMENT file EMPTY>
	<!ATTLIST file
		name CDATA #REQUIRED
		series-uid CDATA #IMPLIED
		sop-instance-uid CDATA #IMPLIED
	>
	<!ELEMENT raw (#PCDATA)>
	<!ATTLIST raw
		encoding (csv|base64) #REQUIRED
		type (T1) #REQUIRED
		unit (s) #REQUIRED
		x-size CDATA #REQUIRED
		y-size CDATA #REQUIRED
		source CDATA #IMPLIED
		source-format (xml) #IMPLIED
	>
	<!ELEMENT control (converter,model,agent,patient,(helpers?),(roi?),(align?),(time?),(fit?),(import-filters?),(override?))>
	<!ELEMENT converter (key-value)*>
	<!ATTLIST converter
		class CDATA #REQUIRED
	>
	<!ELEMENT key-value EMPTY>
	<!ATTLIST key-value
		key CDATA #REQUIRED
		value CDATA #REQUIRED
	>
	<!ELEMENT model ((key-value*),(ranges?))>
	<!ATTLIST model
		class CDATA #REQUIRED
		aggregate-all (yes|no) #IMPLIED
		validate-input (yes|no) #IMPLIED
		validate-output (yes|no) #IMPLIED
		check-persistence (yes|no) #IMPLIED
	>
	<!ELEMENT ranges (key-value*)>
	<!ELEMENT agent EMPTY>
	<!ATTLIST agent
		name CDATA #REQUIRED
		volume CDATA #REQUIRED
		conc CDATA #IMPLIED
		r1 CDATA #IMPLIED
		r2 CDATA #IMPLIED
	>
	<!ELEMENT patient EMPTY>
	<!ATTLIST patient
		weight CDATA #REQUIRED
	>
	<!ELEMENT helpers EMPTY>
	<!ATTLIST helpers
		curve-extractor CDATA #IMPLIED
		onset-locator CDATA #IMPLIED
		roi-curve-extractor CDATA #IMPLIED
	>
	<!ELEMENT roi (roi-x,roi-y)>
	<!ATTLIST roi
		encoding (csv|base64) #REQUIRED
		x-size CDATA #REQUIRED
		y-size CDATA #REQUIRED
	>
	<!ELEMENT roi-x (#PCDATA)>
	<!ELEMENT roi-y (#PCDATA)>
	<!ELEMENT align (align-type,align-offsets)>
	<!ATTLIST align
		roi-x CDATA #REQUIRED
		roi-y CDATA #REQUIRED
		roi-x-size CDATA #REQUIRED
		roi-y-size CDATA #REQUIRED
		image-x-size CDATA #REQUIRED
		image-y-size CDATA #REQUIRED
		dynamic-only (yes|no) #IMPLIED
	>
	<!ELEMENT align-type (key-value)*>
	<!ATTLIST align-type
		class CDATA #REQUIRED
	>
	<!ELEMENT align-offsets (align-x,align-y)>
	<!ATTLIST align-offsets
		encoding (csv|base64) #REQUIRED
	>
	<!ELEMENT align-x (#PCDATA)>
	<!ATTLIST align-x
		type (int32) #REQUIRED
	>
	<!ELEMENT align-y (#PCDATA)>
	<!ATTLIST align-y
		type (int32) #REQUIRED
	>
	<!ELEMENT time EMPTY>
	<!ATTLIST time
		interval CDATA #IMPLIED
		onset CDATA #IMPLIED
	>
	<!ELEMENT fit EMPTY>
	<!ATTLIST fit
		use-images CDATA #REQUIRED
	>
	<!ELEMENT import-filters (filter-type)+>
	<!ELEMENT filter-type (key-value)*>
	<!ATTLIST filter-type
		class CDATA #REQUIRED
	>
	<!ELEMENT override (key-value)+>
	<!ELEMENT results (converter-output,computed-maps,aggregate-results)>
	<!ELEMENT converter-output (data-record+)>
	<!ATTLIST converter-output
		encoding (csv|base64) #REQUIRED
		x-size CDATA #REQUIRED
		y-size CDATA #REQUIRED
		point-count CDATA #REQUIRED
	>
	<!ELEMENT data-record (#PCDATA)>
	<!ATTLIST data-record
		x CDATA #REQUIRED
		y CDATA #REQUIRED
	>
	<!ELEMENT computed-maps ((map+),(supplemental-maps?),failures)>
	<!ATTLIST computed-maps
		encoding (csv|base64) #REQUIRED
	>
	<!ELEMENT map (#PCDATA)>
	<!ATTLIST map
		name CDATA #REQUIRED
		type (float|boolean|int32) #IMPLIED
	>
	<!ELEMENT supplemental-maps (map+)>
	<!ELEMENT failures (fail-codes,map)>
	<!ELEMENT fail-codes (#PCDATA)>
	<!ELEMENT aggregate-results (aggregate-data,aggregate-values)>
	<!ATTLIST aggregate-results
		encoding (csv|base64) #REQUIRED
	>
	<!ELEMENT aggregate-data (#PCDATA)>
	<!ELEMENT aggregate-values (key-value+)>
]>

<mriw-result-set version="1.0">
	<provenance>
		<program name="MRIW" version="4.4" build-id="20100730" />
		<creation user="adminjamesd" time="Tue Aug 03 17:31:19 2010" />
		<platform>
			<machine architecture="x86" os-type="Win32" os-name="Microsoft Windows" />
			<runtime name="IDL" version="6.2" />
		</platform>
	</provenance>
	<input modality="MR" subtype="DCE">
		<reference path="D:\DicomData\MR\TestData\srtf_breast" study-uid="1.3.12.2.1107.5.2.4.7128.19970724153243000">
			<file name="srtf_breast1_2.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.19970724150154907004" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281818520747791" />
		</reference>
		<dynamic path="D:\DicomData\MR\TestData\srtf_breast" study-uid="1.3.12.2.1107.5.2.4.7128.19970724153243000" slices="5">
			<file name="srtf_breast1_7.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281841430543526" />
			<file name="srtf_breast1_12.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281841480463920" />
			<file name="srtf_breast1_17.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281841530467057" />
			<file name="srtf_breast1_22.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281841580488632" />
			<file name="srtf_breast1_27.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842040056350" />
			<file name="srtf_breast1_32.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842090296272" />
			<file name="srtf_breast1_37.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842140299178" />
			<file name="srtf_breast1_42.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842190339834" />
			<file name="srtf_breast1_47.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842240426559" />
			<file name="srtf_breast1_52.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842290487649" />
			<file name="srtf_breast1_57.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842350388544" />
			<file name="srtf_breast1_62.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842400417289" />
			<file name="srtf_breast1_67.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842450479826" />
			<file name="srtf_breast1_72.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842500474356" />
			<file name="srtf_breast1_77.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281842550651683" />
			<file name="srtf_breast1_82.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843000723954" />
			<file name="srtf_breast1_87.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843060547269" />
			<file name="srtf_breast1_92.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843110597673" />
			<file name="srtf_breast1_97.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843160667981" />
			<file name="srtf_breast1_102.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843210694860" />
			<file name="srtf_breast1_107.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843270590799" />
			<file name="srtf_breast1_112.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843320676014" />
			<file name="srtf_breast1_117.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843380477590" />
			<file name="srtf_breast1_122.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843430497962" />
			<file name="srtf_breast1_127.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843480521071" />
			<file name="srtf_breast1_132.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843530588356" />
			<file name="srtf_breast1_137.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281843580570620" />
			<file name="srtf_breast1_142.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844030587024" />
			<file name="srtf_breast1_147.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844090440810" />
			<file name="srtf_breast1_152.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844140410203" />
			<file name="srtf_breast1_157.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844190369031" />
			<file name="srtf_breast1_162.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844240317348" />
			<file name="srtf_breast1_167.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844290340890" />
			<file name="srtf_breast1_172.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844340307838" />
			<file name="srtf_breast1_177.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844400133351" />
			<file name="srtf_breast1_182.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844450095232" />
			<file name="srtf_breast1_187.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844500103301" />
			<file name="srtf_breast1_192.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281844550079960" />
			<file name="srtf_breast1_197.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281845000060784" />
			<file name="srtf_breast1_202.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281845050039969" />
			<file name="srtf_breast1_207.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281845100370561" />
			<file name="srtf_breast1_212.dcm" series-uid="1.3.12.2.1107.5.2.4.7128.20031028173809000052" sop-instance-uid="1.3.12.2.1107.5.8.1.12345.200310281845150833289" />
		</dynamic>
	</input>
	<control>
		<converter class="CalibratedRatioConverter">
			<key-value key="CalibrationType" value="log" />
			<key-value key="CalibrationK1" value="0.15" />
			<key-value key="CalibrationK2" value="0" />
			<key-value key="CalibrationK3" value="0" />
			<key-value key="CalibrationK4" value="0" />
			<key-value key="CalibrationK5" value="0" />
		</converter>
		<model class="CosineModel" aggregate-all="no" validate-input="yes" validate-output="yes" check-persistence="yes">
			<key-value key="PlasmaA1" value="13.5000" />
			<key-value key="PlasmaM1" value="22.8000" />
			<key-value key="PlasmaA2" value="17.9000" />
			<key-value key="PlasmaM2" value="0.171000" />
			<key-value key="AucDuration" value="75.0" />
		</model>
		<agent name="Magnevist" volume="12" r1="4.3" r2="4.4" />
		<patient weight="60" />
		<roi encoding="base64" x-size="128" y-size="128" >
			<roi-x>AAAkQgAAKEIAACxCAAAwQgAANEIAADhCAAA8QgAAQEIAAEBCAABEQgAAREIAAERCAABEQgAAREIAAERCAABEQgAAQEIAAEBCAABAQgAAQEIAADxCAAA8QgAAPEIAAEBCAABAQgAAQEIAAERCAABEQgAASEIAAExCAABMQgAAUEIAAFBCAABQQgAAUEIAAFBCAABMQgAASEIAAERCAABAQgAAPEIAADhCAAA4QgAANEIAADBCAAAsQgAAKEIAACRCAAAgQgAAHEIAABhCAAAUQgAAEEIAAAxCAAAIQgAABEIAAABCAAAAQgAA/EEAAPhBAADwQQAA6EEAAOhBAADgQQAA4EEAAOBBAADYQQAA2EEAANhBAADYQQAA2EEAANhBAADYQQAA2EEAAOBBAADgQQAA6EEAAOhBAADwQQAA8EEAAPhBAAAAQgAAAEIAAARCAAAIQgAACEIAAAxCAAAMQgAADEIAAAxCAAAMQgAADEIAABBCAAAQQgAAFEIAABhCAAAcQgAAIEIAACRC</roi-x>
			<roi-y>AACWQgAAlkIAAJZCAACWQgAAlkIAAJZCAACWQgAAlkIAAJRCAACUQgAAkkIAAJBCAACOQgAAjEIAAIpCAACIQgAAiEIAAIZCAACEQgAAgkIAAIBCAAB8QgAAeEIAAHhCAAB0QgAAcEIAAHBCAABsQgAAbEIAAGxCAABoQgAAaEIAAGRCAABgQgAAXEIAAFhCAABYQgAAWEIAAFhCAABUQgAAVEIAAFRCAABQQgAAUEIAAFBCAABMQgAATEIAAExCAABMQgAATEIAAExCAABMQgAATEIAAExCAABMQgAATEIAAExCAABQQgAAUEIAAFRCAABUQgAAVEIAAFhCAABYQgAAXEIAAGBCAABgQgAAZEIAAGhCAABsQgAAcEIAAHRCAAB4QgAAfEIAAIBCAACCQgAAgkIAAIRCAACEQgAAhkIAAIZCAACGQgAAiEIAAIhCAACIQgAAikIAAIpCAACMQgAAjkIAAJBCAACSQgAAlEIAAJRCAACWQgAAlkIAAJZCAACWQgAAlkIAAJZC</roi-y>
		</roi>
		<import-filters>
			<filter-type class="BinomialImageFilter" />
		</import-filters>
	</control>
	<results>
		<converter-output encoding="base64" x-size="128" y-size="128" point-count="42">
			<data-record x="36" y="53">HUH+OhGrozvQe/O71hzrO8RrbbzcEVs5oEOfPGhLGz3udQA9lB5IPefPej35BWw9NFGLPSWToz1ZVnQ98lyfPTG4rD0obJc96yCuPbXapj1cILY9PeWePTJ/nT3Xx6s9nJq6Pax4xT2XXLY9GVO+PRMh1T3047U97rPTPZdctj3+H7I9FPS4PeMgxz2m49k9LhvDPXTGtz3mRMA9dMa3PVTC4T0lh809</data-record>
			<data-record x="37" y="53">/ja2O4gbpzrc+d/7djTfOrLkjrxZI6/7TaO1PLhJND1TzR09DmCGPX9QYz37LIs9/yyLPY7AoD3Au5I9CL/mPTUVyT14DqM9+J7PPTqnuj0Lu/A9BePEPVNaxT3forc90cnnPVDc2j3Wa8Q9I1HjPWYY2z2Xass9i8TUPUG01T2Ly/s9I1HjPZf10T24fug9cJziPUiN4z3TMuU91HPOPUiN4z1OM/E9</data-record>
			<data-record x="38" y="53">vpyROwXN7rugXzo7cf/2uy9MgLxTYqS7jrwVPYjZTz38uWE9Zv6aPf81Yj0HV6M93WifPVmsnj23UqQ98biqPceo5j1/5q89bH+0PcWoyz1R9u89aWflPXVh2D3Zrcc9WhIBPlH27z2K7cc9k4v5Pacx7T0B5uM9WazpPbUk0D3Ek+w9qGnnPXR0wz2mu+I9S+7zPYrd+z1ZrOk9n6LePdawxT1BffM9</data-record>
			<data-record x="39" y="53">HVnJu0fkc7sppSE87pgou0d6ELzoeqU8XGWKPVFimD1p4Lc9FpvNPRyPrz3IFNI9AbTePdFb4j3te/M9PHXwPfEiDD4p3eY9EAUTPtme+j2cThM/jhYbPmORBT7HtAo/5iQPPkRWFz5lKBI/VC0VPqCnGj6qgho/AncVPpVvAj6xBhQ/UMz5PX6u9j2gpxo/rLQJPiB7Fz5UlRE/DigBPvsQ+D14CBU/</data-record>
			<data-record x="40" y="53">mvOgvEeGhDyIa2M7jqJIPGXtszsRRwA9kZyqPTnMwj1Lotc9onbwPZQO8T2Z1vI9AzAIPisLDj4IrRQ/YIQZPjRbET5K6Rg/EWYcPobiFT5yhz0//JkmPu6MHD5sNic/M6sZPgGQMj7xfjc/EbguPlvLLz7O1j0/bhwhPmWGHj6hJCY/xhgPPqEkJj5eyzM/w/QfPriWKD4+GjQ/S90SPjsGMz6XgCA/</data-record>
			<data-record x="41" y="53">7X5qvBfUejxNqYK60P9XPMTB5zuJmwE7IDFrPemMpD1NrLE9KD+OPUfr8T1FcOM9AyMLPmrq+z0uYgw/bkYLPk5OCj7AfB8/H/wIPr5xCj4l9zI/FjoEPnisFj6M+wo/lMAJPoXMJj5Ahh0/e/gfPhDAID4PAy0/aRoRPqkaHT66tg8/bswRPmg1KD6CNRg/C9gbPkboGD653yE/1yMVPr0iLz4xlQo/</data-record>
			<data-record x="42" y="53">ylq7uvNF6jo1pbu5ANAOuwUF87uscWC8BTA/PfnafT1s1Yo9h/6aPcULuT3U5K09PPrePS48zz0feM89fJrCPd0+6z0TMuw9673ePTjf5D2mTPM9ywrHPUoy9T0m17s9S4HaPRT84j0sGeE9vDbXPaZM8z1isfA9GWTgPTl89D2X/tY9b1XhPeu93j2CkNk9JkXaPXmg4D3sccg9jr+iPezN1T3jkb89</data-record>
			<data-record x="43" y="53">rCl2urjTsToX9Nq5vpYSvMogf7ymkPW7UzdePT5jcD3rUYc9RCKPPTEEjj2Om5M9XH6oPT6cvD2EnbA9ytGePeP3xz0BS7E9XXfFPSnAzD1uSr09XdewPeP3xz2H95Y9+uO5PRoXoz0dr7Q9ZmqiPekCxT06oLc9q2OwPQ0Guz37V7o95QivPanhmT0jPcU9nOabPWt8rz2EVJo9R2yyPSjBgz00vpY9</data-record>
			<data-record x="44" y="53">vgD2u1P/2jugD1g6uOO1OXF1L7yaqpS7u+RGPU0Hdz1rFpg9jl6ZPe8AiT0EDKk9B5iyPe63yj03u7Y961G5PZFvwz0Ui7g9b4/xPSMTxz1mjeM9sv7EPby5vT0EDKk91OGrPXf9tj3FNrY98jS9PTvuzz1vEtk9OguxPWjGxT3sUcA9hQa4PRr8vT3UD9M9rBOyPRGIqD0/Pcs9dUvGPdZlrD0x2rI9</data-record>
			<data-record x="45" y="53">ET9nu/JKwzugVx/7iKs3PIibGjrKtmG8U6bsPAi5WT0UImA9EbWPPffSiT1WHLc9+FrSPbWMxz2oT6I9kCu+PZRgvT34Rb49i/WVPdpttD1ybfU9WiGpPRp4vz1aBrU9UzyOPZM+zT0H0LY9n+TDPdMOwz1ESuk9X/mqPdOlzD1l1ag9Jn/5PRGt2D0Ctbc9LqrAPQgDlT0H9dI9h8S+PTD62D2QK789</data-record>
			<data-record x="46" y="53">mkAaPKz5PDtBf0m83CkWO+pQKzyswIK8ZcGtPNCU+Dy4Moo8Teh3PQGugD3adpc96ZKyPT0nij2jDIA9YpibPbj6qD3pn4c9DrpvPcuIjz0RnbE9DiYxPbj6qD24aYU9gp09PYR/rD04tJI9wGqYPU53hD0U87k9KzSDPXQNmT3R+oA9Y+ONPRFToT3lhIM99YCdPUoGYD01rYY9l7qFPc7pmz16NIk9</data-record>
			<data-record x="47" y="53">F3qWPLg7hrsX1mm8yjqkOgsiTzys7wW8I2S8PAW+XjxBD+g7IHtYPQLhMz3tgmY9OJByPd8AID3uKEM9DiZZPVztdz3HbRU9x20VPX8uZz3oz009QWviPDgwaT2yzhA9Sp8DPQ7ibz2IUyE9u0R5PaZIJz23JKU9UNFHPaxBdz0CNTU9QWQZPSyqID3E1T89O+d9PVNCKz0j7yk9ss4QPU3u7DyLMAw9</data-record>
			<data-record x="35" y="54">0Nc5u6akFrtNPag7Iy6Ou4jjQLuaqoq7lD8JPF+1/Dzcj9A8dgPePIWNOD0UzRQ9dodhPcrtUj3HFyA9MtROPVyzej1xF0c9Ge2EPQzUiz27IGs9Di88PdkMXD047DQ9R79+PVPXaD38okY9nTmHPf36jD0UW2M9ZNR/PfMYTD0RXUQ9VpNWPcQoYD27IGs9izZqPXCuWj1y+Ik9SmJoPVzTcz3EKGA9</data-record>
			<data-record x="36" y="54">EbdiukfMCbsLekI79K2vu4PgmLzcMUW6F6wHPFNzDj2yNfc81sgZPRoWTD1+8UQ90P/CPXiIiD18kEI9nwmCPWjwkT2groQ9pmCjPdeYlD0l5KI9ZMp/PZ0Whz04IIY9BaaiPa4RnT0UNqk9rNWkPe62sj2s1pQ9fVecPfEDlz2uHI090EqIPXStmT3HjZ09HY/OPb4Tjj2Nnqw9FFFyPb8BsT3p1Y09</data-record>
			<data-record x="37" y="54">poxgO8piYLsdcSe2BbVKu197pbxlTWq5TV/fPCNnVz1fpTc9mdyIPa9Dhj1aBaw9YzC+Pd1exz3sXa89wQ7JPWXVwT1sm849TTvSPd1exz2WJgY/Yv3RPSCW1j2Ljeg9PK+3Pent9z2J3QA/KhzwPe1C9D0jjfI98+j1PeFL+j0qhQY/PK+3Pcz4CT4wEv09wWX5PcRxAz462Qk/JkngPWt8Fj71y/g9</data-record>
			<data-record x="38" y="54">X/ihO/hhILxx2547ysIPvO7/MLxHULo7pocpPeBShz1Btog9Tki4PWBooT3WF809JsjoPR360j1UWtE91kD0PTxV9z3IseQ99Zf5PVBj/T2E5wk/JgwCPsxQBz7/ePw9Sk0UPrI9FT5qCPs95ZkMPmbfAj7GHg0/V3IQPuHwCj66rQ4/xh4NPs4tCT5USAk/ZlgVPrI9FT7izBE/ihwKPk4BBz5UmAM/</data-record>
			<data-record x="39" y="54">fVWUOwu4XrxNjRQ89KymvLgSgryUDLw88ZKPPQL3rD0dLL89r1rYPd2OsD2THtU9v7fwPXWD1D3XcN89gZv/Pdz4Dz6QOd49s94aPunDDz4dP+c99hMTPpoKDz6+t+A9iAofPon7FT7Ifu89A0kNPl3SBz6ptAo/3msOPuDjAj6Bm+49GSwCPkGrzz2wnQc/oDgLPoFlCj4VwwE/ZBgDPlwKzD2WqQU/</data-record>
			<data-record x="40" y="54">L+Bbu3aEZLoviIo7R4ZPvNAfkLx6dC09wo7mPfBtAT6yoBY/sqAWPm9YCT7zwhQ/T48kPt1dGj6D8yk/9MIqPh6lOj7R/yY/6kBYPlsWRD7lPDc/e7JGPlX3PD6jvDs/xUZOPmcMRT5Rmz4/XNQ8PiiESz4FlEI/lPk+PhluMz7BYkA/2gUzPipGIj43hU8/Aho3Po3WPz7UjTk/5Tw3PqiHMT5IP0c/</data-record>
			<data-record x="41" y="54">1vBQvFOWjjwpd5i7moqMPEGPgjugXxI9qQziPaukDT4qcC8/v+M0PjCiSz7fm0Q/VoRbPvb+VD66jF0/aO9iPmjvYj57YXQ/iptnPhCqYz77YYM/M/phPnthdD6wxHs/3AVnPjeofD7NMII/vElxPso7gz4G7IU/GyRxPq1AeT5dmIE/ES93Pu2NgD54voE/qnp3PtWkcz6f638/Bf55Pjkfij7urHQ/</data-record>
			<data-record x="42" y="54">+992uy/c8ztNWXC75yNyPFPWHju4qL48b8bAPV8O9D2Ysw0/xbYZPo5eNj7RcS0/P1I4PtywPz4u7jk/8tFFPnTPQj6L800/9x9FPnXYQD7uhVk/txQ7Pjo3UT45FUQ/nQs6PuHVSD7qHEo/RQBCPs0WTD55sV4/3LA+PhhiUj69q0w/lvNIPvfZQz7If0A/5UVDPqBPOz7qiUE/2R1CPq7iQT7VAy4/</data-record>
			<data-record x="43" y="54">7Vh3O0Gv+bp2BPG6iDtNuVnHTrwFmcM87QnnPVtaAD7aIQc/asgPPpjvFz6H+Ro/HXsYPrEBLD4jwyI/HlwpPhUzMj6SlCk/rXA+Pu7AMj5yMjM/sQEsPkj9Lj7+nB0/C+AmPlaxHz4X0R4/EbUePsvjLD4Ixi0/A0kdPvigJD7uoyM/BA0ePgdEDj40YyY/g1IVPhpkFz7CzBM/0rwWPm1X/z2RpAg/</data-record>
			<data-record x="44" y="54">TRm4Ocp6dbojbhk69FUZu+lSdLyI0tE8NiIGPtTQDz6kNBU/7uMjPpoZEz4RBCo/k4woPgk2PT4onis/Ea83Pmc8Rz58mzY/qFVFPvenRD6Wx0c/RvpDPvq9Nj4WBi4/4hE2PqhcLz7Mvyk/ogoyPkb6Qz4CITU/vgQsPvjhKT7EnSc/1OMtPmhaJT4ekkM/KJ4rPutqJj40oS8/Y2ssPozvGz7Wvyc/</data-record>
			<data-record x="45" y="54">skYCu6D+STsAcI/6NbEqPMSdzznWxiU8i2nfPTAhDj799gc/EsQ4PojjHD6SDUI/6LFOPpPITD6OFzI/IGVLPuUBSj4avU8/FVc7Pm8sTj4jaGo/FJVHPkunUT7NvlM/A/M8Pg8QVz6Zt0Y/kNVJPuA4Uz4Sw1c/cgZGPnHBRz4uKEA/iH1VPnOqXD4iklM/4VBVPkRDPj6MtGA/byxOPrjCaj75j1o/</data-record>
			<data-record x="46" y="54">mlojO00TBzwv6i/8uIldPHZUezzcvc/7jEuFPWxAzz3sW6w9SJghPiR1CT4O0yM/5VQzPmDGHD4khhE/MdooPkw/Jj7/Sig/PasNPu5tJj4yND8/lwEKPtD9Oz5/RDE/i2oXPnyPQz6I1DE/BfYsPiXlIj4XK0c/0TQvPkoVLj4U5TM/E5Y1PiYURT5uqig/kSk5PnlWIj4vIUQ/uJQvPtMwUz7InEI/</data-record>
			<data-record x="47" y="54">X1CjO19QoztfUCO8QfV4PNwjgzwFIb67Jp8jPRpcTD2C1EI9pV+UPebGrD0Qq9M9kJ3ePXh8vD1Xybs969jcPcv69D0jBdo9N3mtPS9o5j2veOc9tH61PaT4/T0cFNU9tdfWPXJB+j2veOc9gGQFPpn20j0bbRk/w1gCPgDUBj7mwvY9xxfhPXEFAD4EVvU9T/oAPkIF6z0xmgo/tgr7PS2x9T0GfwQ/</data-record>
			<data-record x="48" y="54">sh6MO/gDYLvK2mC6R3hsPHxxf7v0nSu7jlnfPGVSxzwFsSY9LB5rPUr+Pj3dvoo9TamHPXkIZz2vgUo96deBPYDypT3dCZ89R3lIPQqskz0ytJQ9Zyt8PTfVjT2FfHs9phyXPXhHnD2MSoY9FD//PUPlgz1W2rw9uz6bPe/S0z2LLZk94eZ/PRNLpj3mzJc9BYejPd0FqD0+z7M9cZCtPefXbT1xkK09</data-record>
			<data-record x="35" y="55">+6+Cul9wurvoG/s7ykI1vLhD/7rKRgm86PcqPO7pCT2I6fY8evMXPZRsQD1igxI9o2VbPfd/Oj21lTk9oFN4PW46hz3W5lU9Qc5yPeE7fz1+BnY9jtcxPY7FXD1BZTY9FImDPYXcZj3Nd0o9bHaKPd/gej2vkFk9TaV0PVDRVj1rG1k9iMhRPUSwXT1umT49x7JSPZRsQD0DB5M9wYhqPXzwWj3W9z89</data-record>
			<data-record x="36" y="55">OyKrui88Fbx3oCo8TUCbvB0iv7wdXzm8R3zyOqa+5Dy/Dtk863kCPeWjET24TfY87v80Pet9NT39ehk9r949PTvVdz0/6To9+8x+PfljbT0CW3M90xsTPeidUj1HKCs9e6KGPQWFXD35Y209ps59PVBnaz1N72Y9a4dbPW3tZz0/6To9GnY3PWUnTz1r1EA9lLFLPZSxSz1o4oY9lKoqPRpMQz2dmS49</data-record>
			<data-record x="37" y="55">xN2eOTuit7vWtK07prAjvNaJl7zcEfm6NZ0bPKNuJT0/zgU9a2pVPR2zYj21enI9CH2dPV+8oT1p5IE9brygPSx9pT3ZvKQ9GYSTPdP8nT3X+sk9pp2EPcr/qD34R7I9Ry3EPaOcvT0FmtE9MUOuPb+LtD0cGNE9n9K4PdrEyz2xjs49B0u0PaVM3T1xKsM964y1PR9rwz3/YNM9qLyjPbgo7j1oQKs9</data-record>
			<data-record x="38" y="55">sg4NO9AXIrk17QK77hghuyljMTsv+Hc8Bd0xPeDFgj1DdYo9EPa1PY2cxz0iINY9bKYBPj4/7T08nN09jpMGPvB0/D3Qo+c9B3PNPbA57D0TGws/o/zlPbH1BT6sWgk/Pe4LPvjRET6LVhI/WeECPlFrBD6j5hY/zdoPPt6UDT6WShk/LhcHPrdhFj6fgxQ/Z7kLPra3Dj6GghE/BQkFPi5hID5oswM/</data-record>
			<data-record x="39" y="55">pjCDO8pa7boLsg/7ERlgvEdcM7wp+vI8BfudPenvtD22Zc09mXXbPVyB4T0F6fU9muMIPq/m/j3pTwE/2bsMPguIET4zD+89FXIRPilGET59IwU/RZ8LPrLREj7itwg/dO8dPo4DGT5XgAY/dwQOPungCz6OMRQ/2ekVPsTRDD7p4As/DaIIPlYt8T2OAxk/O2QMPuzmDz5GpgU/0VAJPqY+9j2xZgk/</data-record>
			<data-record x="40" y="55">L8zNOyP2wLvcUc257r6vvE1R87yR4iU9QofrPftv+D1npwk/ED0NPnHNBT7R1BA/SzccPv4rFT5b/x0/OeUZPh3wLz6E6ho/1/JMPtBmPD79phY/xHcvPisIMD4fqB8/GzQ/PsOhMT5oohU/cJ4oPgnGKj4rByc/C24rPpwoJT6E6ho/FywiPkArBj5eBjU/Dk8cPmanJj6wJxQ/FywiPuyAAT6KOSQ/</data-record>
			<data-record x="41" y="55">yso0OxEn9Topr5e7Zc2cuQtSTLx2b3Q9L8QePgOeMT585Uc/Y09XPnZRWj7f/mE/4gJuPtkecj41THE/PGtvPhM5fz5noX4/A7yLPl6Igz6fgoE/MhiBPpQshz4EVYE/E9iEPqo3hj4RcYA/6iyDPttwhT5C6Yg/fL/BPom5hD78KYI/ZieBPtStgD43S4c/3FN9PrdOeT7Hf3w/Ep58PhlNdz7xXHg/</data-record>
			<data-record x="42" y="55">vmDXOX0dATwM2Ae8KaqmPDWTBzxL/pM90aAxPvx1UD6inGk/cVR/Pi0Uij4lQI0/I3SLPjjAlT68+pM/xPaWPszYkj7E9pY/tlWZPh0mkz6V0KM/NouYPvR3mz4RSZs/LweTPjaLmD7hUpw/PwGaPk2dmj6SH6Q/IIqUPh7Mmj6//Z0/WLGTPqPomD7foZM/HSaTPl8NjD4yLZQ/WpeMPu2Ckz5064Y/</data-record>
			<data-record x="43" y="55">vqAwO8pysjoR7YS7CxJaPBGfw7ogJ5A9U59EPh0YYD7DyWo/LEd8Pr88gz6ABYg/dVSEPus9jT6JHY4/yvCNPnfdjz6boIo/wvaXPqUIkT7luZY/OdmSPjsRjT4/po0/f/6JPoFPiD7/wYk/dK/KPk4KkD7NyYs/2NOFPgtPhT4pt4g/1E/APkVJeD6JbIU/SdJ7PipAez4Ic34/khl1Pi2ldD6btWw/</data-record>
			<data-record x="44" y="55">O6LpOYIuL7qUdWk5HZcQPJpY8LspF549FFRgPgufdz5204A/bpuNPoDchD40UI8/v3mQPg0BlT7qBZE/q/2PPg6cnD7p6ZE/ZSOhPmiDnT5DQJo/GRuWPi4ikD7HnJA/p4CRPjstjz4bkIc//YmNPsVqlT7iaYY/M//JPneSgj59yIM///qDPjDBdz4tuY8/s2OEPlHXgj5sE4Y/d5KCPhNugT7+BoE/</data-record>
			<data-record x="45" y="55">mrLcutaEUzsRV8q6rPNRPE0REzvKSpk9SW1cPgYTej57+4A/OmiaPlSjiD40Dpg/5ICcPk0xmz4XbJI//suZPlPenj55t5s/UNuhPnO2oD6JAaY/Xn/UPtfNmz6qHZ0/tdaWPnrjoD5Nu5E/uw6WPk3imT4mXZU/MmmUPgoCkD6xi5M/afqTPgtTlD5EqpY/uDqYPoHIkD6wrZw/mBqVPqBXnj4/A5k/</data-record>
			<data-record x="46" y="55">cQeWOQDiFTw7khq8QXuWPClhpDy1DSE9qZgRPg4/Mj6l/ic/a0ZrPmuoTz48dWA/kvtxPpm/aD5Fm1Y/ZBV5PlnNdT5GiXg/MH9lPpL7cT50bYQ/xaRUPl/ghT6bT4I/sOVuPiMPhD5GiXg/M4d0PtrNbz6yJoQ/j7Z2PoH7cz5CmYM//xJ1PsiMhj5UwmY/+L/APlnNdT7Ow4w/7R1+Pld2iz4UvIY/</data-record>
			<data-record x="47" y="55">X3ASOl+gZTygB2/8U8fkPMcBBD2a6ls8HUCDPbUBrT3LYJ49ybMNPshIBD5WywU/VO8bPszfGD4q7wA/EjIgPos8KD4rdjQ/c4X9PYgMIT5r8TM/T0cDPihdNj4S6DI/NDUnPvJ0Lz53mC4/+NUwPiOWIj4Op0E/v2wzPm4lMD7hSTQ/fKMkPoxxRD4/7Cg/aaI0PvKYMz7uHlI/o3k9PuI2Pz5FnkQ/</data-record>
			<data-record x="48" y="55">9B2Gu6ArfTziHDq84u6mPNCxczwX0L07r18NPZqfKT2sZEU9MhWYPTdEpj2gPa89O4PCPR2NuD24ZJQ9pWq6Pabyzz2FvvU9YJOKPRRhyT3vhvM9kcujPRyhyj3CWtk9QZHLPeVhzj0cIN09OWnpPZpBxj3QQOw97JXgPbLd/T0yyuI9UDHMPb6FBT5ZPds9TdXnPVbY4T0ty+Q98i76PQiu5D2WQ+89</data-record>
			<data-record x="35" y="56">d4i9O1PCmbuOGI/6KUN5vO5EIryI7/G7QTaVPCDZEz21aBE97h9RPXMnTz1BN0s98CF7PXNzXT0UvW89hbihPas1kz3T+Yg9oDZyPas1kz1/tp49dDtKPRb+hz24mn49lrWcPdk0lj2/9Jg9lrWcPUP3jz09eY09tfihPSx1lD19tZM9rvyJPSx1lD0jSWs9i+qjPUe+hz0CPqc9TrWbPem0lT1HA4U9</data-record>
			<data-record x="36" y="56">Uw4ZO/7sx7t2zHY7Iw/jvPl99rymJB68BrSPPN/wHz3iMRs9LFtRPTUxKD1NtzU9oJ9tPfCAYj0/J3A9oFSJPTT1mz2vlYk9ALWBPWMopD21s5s9i+pfPWwTiT2A24o9RfSlPbWzmz3FB589U0mfPZEQqj2x5qM9q7mvPRkOoD3LJJk9nAqHPWhHhj2dHIs90HemPbe5nD2x5qM9wLyRPYDbij1c45g9</data-record>
			<data-record x="37" y="56">jryLu45gF7vWbNc71nIpvB08vrwRa8C7jm23PN/3Oz0pjDA9QYuBPUqhUT2RPGI9Kb6XPYiynD3cC2s9fSugPfKZwT3Q4KY9+siTPcpVtj2R46Q9Dq6IPYBbqz0Zp6I9Rx3FPcKcxD3K1bg9KBmuPX/Wuz1joMc93RurPdNWsj1gVrM9FFmuPe+xnD3oFbU9VJazPRmnoj2alrI9hWeiPZwWvD3TZaM9</data-record>
			<data-record x="38" y="56">gzqZu2XNHDuOqBU7cAfmufoekrtl9Rc88LdYPe+9hj2iJaE9PzbKPcU15D2oKes9hq8HPnGYAj4Uf9g9lzwKPuN6Cj61Wwo/VjbZPdro9z2PJAk/bFzbPdMrCD6bAg4/dEcNPpGxED4Gphg/WjMDPv1pCD5/2RQ/i58FPhyJCD5rxRg/4ngGPkMoDT4nGBU/EU4MPoZ5Aj61Wwo/or4FPgBWJT77SPs9</data-record>
			<data-record x="39" y="56">rPkeuxeg2Tu4I4q74ia+u9YYM7zNOQs9UBK/PYty0T1bAgM/VA0IPgi0IT4dfCU/LtstPijDKT46qik/ePswPhCKLj4JQTI/oDQoPgPKKD4mwzY/6FsmPhDVLj7xX0M/8cw0Pq6BND7tvj0/RGUwPsLDMT50qTw/Blo9PnNKNT7yq0M/8eIoPkBeLT5VqUQ/GFoyPhFzNz5AXi0/PUwwPoMzOj4uICs/</data-record>
			<data-record x="40" y="56">iOtMO7gDqjntLGK7R5VjvH8ksLxmikg9rnL7PYBHCz7qNho/bkoiPuB8Kj7NhS8/KS42PiolNz7IvkA/7GI3PubgQT6egEA/dbNZPhcyTD4xkzs/LLhHPs94RD4zIEg/Rh1MPnXnQz4zvjY/5NlFPluVQD7k2UU/8GpDPruiQT6/bjg/gwEyPuIjJz6Qm0U/ofk0PoJCQD4TKiw/FfM3PvW4Hj4cPzI/</data-record>
			<data-record x="41" y="56">g2QIPIjV4rsFzbe6L788vBQohbzmDo09KpssPmMjPT65FUY/pihbPvfzVz5952Q/7slmPqpubz6QxHQ/P9NrPhcfez7JN3Y/u/qNPoWtgz6NxXM/B52APgedgD7VZ3Q/cIiCPuDCfT7+bWY/MiiAPosgdj7RIH8/bVttPjOXcz4qUmE/cxVlPusYZD700Gw/Vx1qPv6EZj6w/l8/FBJmPr9XST7uHl0/</data-record>
			<data-record x="42" y="56">C4CPO6Y0d7voKx/6jlQKO6BvB7q0Ask9De9yPgS7hD4Y040/RNWZPlPKmj5VM6g/yBqgPgsYqj5q4Ks/KkSqPrx4rj5YB6g/5u/4Pl0IsD7+SrI/ZquwPhalrj4dZaw/KVuuPq2grz4Lhak/PGyxPrx4rj4PybA/HKGjPopIpT5rbaQ/ZGOgPjjipj5IqaI/BXykPp1enD4x5qA/5aacPrbDmD7ACJg/</data-record>
			<data-record x="43" y="56">iA9vu1m+FTtfoLI6CzJiPH23rztFAfg9c4yWPsr/pj7q6rI/YBm7PnufwD4BNs0/TAnEPpz5yj646M4/ofLIPhujzj7WlsY/w2LXPq2z0T7iudI/t7nPPuQAyD7sitA/o2XHPu4xxz5CB8o/GKvMPuyK0D4xKsM/uCe+PknCvD4bKcI/zx64PoqXtz4bKcI/7Am6PuYNuD4+kLs/rrSzPtJktz46grM/</data-record>
			<data-record x="44" y="56">4rKwu4jL0zu/YIy6L7aYPAVP/TuCmw8/nrmiPgDWtD7cTMQ/QFHNPpEqzT5XINc/e4fUPuRx1T4Cm9Q/JmDKPmQo0z4Qg88/MZXePva62z6jaNE/Ri+MPt7Rxz7gidM/3tHHProYyT4+2MY/rg3LPk77zj7r07s/aZXCPoTTvT5AQcM/GYq5PnoatD6fuMU/Kcu6PjKkvD7DpcA/V6W6PlJ1uz5Gkbw/</data-record>
			<data-record x="45" y="56">9NXDOinToDsdydG7d3sOPEF8EDw+MgI/GyqTPvIfnT6BIqc/1LCzPqaYpz4olrY/C920PvvAsj4jAK0/X/mqPtKIsz6kxKw/l6y6PtkUtD40S6o/G9eiPjwPqT6p6qs/z9SkPsgnrT7e+6E/tV2oPnD7pT6FOqI/yXOjPn4/oD6bTKM/6JecPsrdmT7RRp0/NFeePrVtnT44daI/+HahPvTOnT71JqI/</data-record>
			<data-record x="46" y="56">F9T6O76Anjsvqky8BaHtO+R7kTysHp093/lPPvEGWz5/SVQ/fHp1PlFtYj6pcn4/8OCBPhMUez4c2mY/88t5Pv7qhT5sIH4/mZJ+PvsneT5fJ4E/FdljPkLWhT7qWYU/XVx0PpoWgz5xZXc/TuF7PvfWdD6i3YQ/yuFzPh/Qcz4+4Hc/zshuPgjWeD6IAWQ/TuF7Pp8Vcz5K7YI/jRN3PlnAgD7qxH4/</data-record>
			<data-record x="47" y="56">cRcQO9wJmDysDKq81i7yPH1JJT16kQs9LgTBPTON6j3cr9M9LhAdPiHOHz5qDyg/F+g8PmNsNT6rRRc/A0ksPtdnNj5t1ks/NCoaPnjzMz5OKFM/xbcYPlTaSD6zgVk/Hd04PvqDST6lYEU/Xyk7Pi5XOj5jqFM/XI03PiADOj5vPUI/Q+86Pqz/VT6i/zs/YKlOPm3WSz5R1lg/VgZIPtaFXD74+0w/</data-record>
			<data-record x="48" y="56">vjyhuztxuzzuIZO81k2hPI4G8TxN9TM8tYwQPfx4Vz3uoUI91vqyPa/7wj3fLc09Cpb0PdpF4T3cKL89tZDSPfBC1T3Ngwc/uKWtPbih7T0odxE/4iqsPUsQ3T18ygI/+ELbPYLj9D3S4AE/wavgPc257D2ZEv09zl7gPbBP6j3muQE/tRrpPfbZED6ZrfM9f0n/PdLgAT6gEvM90uABPmc/Dj5fgP89</data-record>
			<data-record x="35" y="57">HeXsO1OW47uI/5S59EqBvF8MK7yUIZg7a4kJPU1iZz0jE0w9NTWVPRnpiD1o85M9KwyhPRpapj3R1aQ9LKrIPQtsvD2LALI90feWPVba0D35r8k9qHiXPbG7vz169a49O9XZPctoyD1uks89iNXEPZzryD2ZPsw9LHHUPfmvyT2dwcw9dXq+PYJuyT0xqqs9GRjrPf73vj1cJ8g9xBbFPZk/zD3UysI9</data-record>
			<data-record x="36" y="57">9EUVO1kzFbtxR5y1ZTqKvBHH+7zWLDM7TUQcPQ4Mbj07EFE9fQiRPbHvgT1pyps9RLGgPSlOqD33Sak9jkO/PeZvxz2j9MQ96C6hPVke1z2rBr09iqmxPasGvT01OsI91iTPPc2f1D1NJ809UF+VPe9e5D2c39Q9JZ3fPQpryj3EXdg9I37APRb3rT2rBr09/F3iPYivxz3IxL09JrXEPThgtD0j78c9</data-record>
			<data-record x="37" y="57">Ne3Nu/5QDDu/xIc7uFsJvHa8yryaygM8mt5TPX6Ujj2le5A9cWW6PYrsmz0io8E9CuXIPawc2z1mSr09ZYzdPS12/T3ySug9/FrbPaXx7D0Ir8898kroPdHC6T2l8ew9+2TvPR1GAj6HkPM9wgD3PUgdBT5IxvU9SMb1PY0X8j0p/Pg9Lzf5Pe5BzT0LTfQ9qgMDPopQ5z0lhOk9GvzqPS8A1j37Td09</data-record>